const SETSAFEID = 'SETSAFEID'
const SETCRIMES = 'SETCRIMES';
const SETLOADING = 'SETLOADING';
const SETERROR  = 'SETERROR';
const SETERRORMESSAGE = 'SETERRORMESSAGE';
const SETLOCATION = 'SETLOCATION';

export {
    SETCRIMES,
    SETLOADING,
    SETERROR,
    SETSAFEID,
    SETERRORMESSAGE,
    SETLOCATION
}